# Generated by Django 6.0.4 on 2026-04-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayigamba_david', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_user_list', 'Can view list of all users'), ('can_access_instructor_panel', 'Can access the instructor panel'), ('can_access_admin_panel', 'Can access the admin management panel')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
