# Generated by Django 6.0.4 on 2026-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayigamba_david', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='kayigamba_d_usernam_f956c4_idx'), models.Index(fields=['ip_address', 'timestamp'], name='kayigamba_d_ip_addr_e8c5a4_idx')],
            },
        ),
    ]
