# Generated by Django 4.2 on 2026-04-14 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kayigamba_david', '0003_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registration', 'User Registration'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirm'), ('permission_grant', 'Permission Granted'), ('permission_revoke', 'Permission Revoked')], db_index=True, max_length=30)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='kayigamba_d_event_t_b6708e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['username', 'timestamp'], name='kayigamba_d_usernam_7517e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='kayigamba_d_user_id_3b1e72_idx'),
        ),
    ]
